### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by msafrin3** [franciscop/lobe#1]
hi, can you show how to use this. Currently im using Lobe desktop application. Or at least explain where to get key value (process.env.LOBE_KEY)

**Comment by franciscop** [comment]
Hey sorry "This is an unofficial package!". When I created it there was an API and webapp where you could login and manage your projects, but I cannot find it anywhere anymore so _I guess_ it's discontinued.

**Comment by franciscop** [comment]
This is the API that there used to be back then:

[API intro in Archive Org](https://web.archive.org/web/20180607183146/https://www.lobe.ai/)
